### ISSUE TITLE
InteractiveAuto

### ISSUE THREAD

**Issue by codehunter13** [mr-azazael/LightweightCharts.Blazor#7]
Hi,

Im using the .net 8 Blazor Web App template with rendermode InteractiveAuto applied globally.
When running i get the error:   Microsoft.JSInterop.JSException: 'There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.

I tried the same Webapp template, the same rendermode but applied per page/component.
I made a page with a chart in the server project (rendermode = server) and one in the client project(rendermode = WebAssembly).

Both pages are giving the same error if i open the other first. So
open server side, than open client side => error
or
open client side, then open serverside => error

```
Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
Error: There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
    at v (https://localhost:44307/_framework/blazor.web.js:1:2037)
    at e.invokeMethodAsync (https://localhost:44307/_framework/blazor.web.js:1:2428)
    at Object.lightweightChartsInvoke (https://localhost:44307/_content/LightweightCharts.Blazor/lightweight-charts.scripts.js:19:45)
    at https://localhost:44307/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:44307/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:44307/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:44307/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:44307/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:44307/_framework/blazor.web.js:1:81802)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at LightweightCharts.Blazor.Charts.ChartComponent.<JavascriptInvokeAsync>d__53`1.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 436
   at LightweightCharts.Blazor.Charts.ChartComponent.<Options>d__38.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 287
   at BlazorApp1.Components.Pages.CandlestickSeries.<InitializeChartComponent>d__13.MoveNext() in C:\Projects\GSL.CryptoHunter\BlazorApp1\BlazorApp1\Components\Pages\CandlestickSeries.razor.cs:line 96
```
Regards,
Glenn

**Comment by codehunter13** [comment]
I posted the problem also in Microsoft's GitHub and it seems you need to adapt your library to support the new interactive auto mode. See https://github.com/dotnet/aspnetcore/issues/53330

**Comment by codehunter13** [comment]
this seems to be the line  (inside lightweight-charts.scripts.js) that goes wrong:
result.UniqueJavascriptId = await DotNet.invokeMethodAsync('LightweightCharts.Blazor', 'GenerateGuidForJavascript');

I think it's the only place where you call back into .net from js. As it's just to create a guid easily, i think you can just replace that function with a function that creates a guid in js 

I fixed it like this:
```
lightweightChartsInvoke: async function (target, method /*args*/) {
    var args = Array.prototype.slice.call(arguments, 2);
    var result = target[method].apply(target, args);

    if (typeof result === 'object' && typeof result.then === 'function')
        result = await result;

    if (result != undefined && result.UniqueJavascriptId == undefined)
        result.UniqueJavascriptId = this.createGuid();
    return result;
},

createGuid: function () {
    function _p8(s) {
        var p = (Math.random().toString(16) + "000000000").substring(2, 10);
        return s ? "-" + p.substring(0, 4) + "-" + p.substring(4, 8) : p;
    }
    return _p8() + _p8(true) + _p8(true) + _p8();
},
```

I just took a create guid function from https://www.c-sharpcorner.com/blogs/generate-guid-using-javascript1

**Comment by mr-azazael** [comment]
Hello,

Thanks for the fix, 
I've changed that line that was using the DotNet member with a function from those linked by you.

Also, I've updated the sources and build a new package for the latest version 4.1.2 (this fix is included).
